<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$config['base_url']	= '';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
//$config['uri_protocol']	= 'QUERY_STRING';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = TRUE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
if(TEST_MODE)
{
$config['log_threshold'] = 4;
}
else
{
$config['log_threshold'] = 4;
}

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] =realpath( ROOT_PATH).'/mis/logs/';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'mis';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

//auto load config
$config['auto_load']=array();

//smarty config
$config['smarty_template_dir'] = ROOT_PATH .'template/mis/templates/';
$config['smarty_compile_dir']  = ROOT_PATH .'template/mis/templates_c/';
$config['smarty_config_dir']   = ROOT_PATH .'template/mis/configs/';
$config['smarty_cache_dir']    = ROOT_PATH .'template/mis/cache/';
$config['smarty_plugins_dir']  = ROOT_PATH .'template/mis/smarty_plugins/';
$config['smarty_force_compile']= false;

//menu
$config['logout_url']='/index.php?c=index&m=logout';
$config['menu'] = array(
array('title'=>'明星库',   'url'=>'',
'sublist'=>	array(
array('title'=>'创建明星','url'=>'/index.php?c=artist&m=create&tn=artist_add'),
array('title'=>'已发布明星','url'=>'/index.php?c=artist&m=search&tn=artist_list&search_status=0'),
array('title'=>'未发布明星','url'=>'/index.php?c=artist&m=search&tn=artist_list&search_status=1')
),"prefix"=>'artist'
),
array('title'=>'专辑库',   'url'=>'',
'sublist'=>array(
array('title'=>'创建专辑','url'=>'/index.php?c=album&m=create&tn=album_add'),
array('title'=>'已发布专辑','url'=>'/index.php?c=album&m=search&tn=album_list&search_status=0'),
array('title'=>'未发布专辑','url'=>'/index.php?c=album&m=search&tn=album_list&search_status=1')
),"prefix"=>'album'
),
array('title'=>'单曲库',   'url'=>'',
'sublist'=>array(
array('title'=>'创建单曲','url'=>'/index.php?c=song&m=create&tn=song_add'),
array('title'=>'已发布单曲','url'=>'/index.php?c=song&m=search&tn=song_list&search_status=0'),
array('title'=>'未发布单曲','url'=>'/index.php?c=song&m=search&tn=song_list&search_status=1')
),"prefix"=>'song'
),
array('title'=>'MV库',   'url'=>'',
'sublist'=>array(
array('title'=>'创建MV','url'=>'/index.php?c=mv&m=create&tn=mv_add'),
array('title'=>'已发布MV','url'=>'/index.php?c=mv&m=search&tn=mv_list&search_status=0'),
array('title'=>'未发布MV','url'=>'/index.php?c=mv&m=search&tn=mv_list&search_status=1')
),"prefix"=>'mv'
),
array('title'=>'演出库',   'url'=>'',
'sublist'=>array(
array('title'=>'创建演出','url'=>'/index.php?c=show&m=create&tn=show_add'),
array('title'=>'已发布演出','url'=>'/index.php?c=show&m=search&tn=show_list&search_status=0'),
array('title'=>'未发布演出','url'=>'/index.php?c=show&m=search&tn=show_list&search_status=1')
),"prefix"=>'show'
),
array('title'=>'影视库',   'url'=>'',
'sublist'=>array(
array('title'=>'创建影视','url'=>'/index.php?c=yingshi&m=create&tn=yingshi_add'),
array('title'=>'已发布影视','url'=>'/index.php?c=yingshi&m=search&tn=yingshi_list&search_status=0'),
array('title'=>'未发布影视','url'=>'/index.php?c=yingshi&m=search&tn=yingshi_list&search_status=1'),
),"prefix"=>'yingshi'
),
array('title'=>'标签库',   'url'=>'',
'sublist'=>array(
array('title'=>'创建标签','url'=>'/index.php?c=tag&m=create&tn=tag_add'),
array('title'=>'标签列表','url'=>'/index.php?c=tag&m=search&tn=tag_list'),
),"prefix"=>'tag'
),
array('title'=>'配置词典',   'url'=>'',
'sublist'=>array(
array('title'=>'创建单词','url'=>'/index.php?c=option&m=create&tn=option_add'),
array('title'=>'单词列表','url'=>'/index.php?c=option&m=search&tn=option_list')
),"prefix"=>'dictionary'
),
array('title'=>'用户管理', 'url'=>'',
'sublist'=>array(
array('title'=>'创建用户','url'=>'/index.php?c=user&m=create&tn=user_add'),
array('title'=>'用户列表','url'=>'/index.php?c=user&m=search&tn=user_list')
),"prefix"=>'user'
),
array('title'=>'回收站',   'url'=>'',
'sublist'=>array(
array('title'=>'明星','url'=>'/index.php?c=artist&m=search&tn=artist_list&search_delflag=1&search_status=1'),
array('title'=>'专辑','url'=>'/index.php?c=album&m=search&tn=album_list&search_delflag=1&search_status=1'),
array('title'=>'单曲','url'=>'/index.php?c=song&m=search&tn=song_list&search_delflag=1&search_status=1'),
array('title'=>'演出','url'=>'/index.php?c=show&m=search&tn=show_list&search_delflag=1&search_status=1'),
array('title'=>'MV','url'=>'/index.php?c=mv&m=search&tn=mv_list&search_delflag=1&search_status=1'),
array('title'=>'影视','url'=>'/index.php?c=yingshi&m=search&tn=yingshi_list&search_delflag=1&search_status=1')

),"prefix"=>'recycle'
),
array('title'=>'待同步',   'url'=>'',
'sublist'=>array(
array('title'=>'明星','url'=>'/index.php?c=operate&m=search&tn=synchronized_artistList&search_type=3&search_audit_flag=1'),
array('title'=>'专辑','url'=>'/index.php?c=operate&m=search&tn=synchronized_albumList&search_type=2&search_audit_flag=1'),
array('title'=>'单曲','url'=>'/index.php?c=operate&m=search&tn=synchronized_songList&search_type=1&search_audit_flag=1'),
),"prefix"=>'operate_record'
),
array('title'=>'统计平台',   'url'=>'',
'sublist'=>array(
array('title'=>'进入','url'=>'/index.php?c=search&m=run&tn=statistic_form'),
),"prefix"=>'statistics'
),
array('title'=>'操作平台',   'url'=>'',
'sublist'=>array(
array('title'=>'进入','url'=>'/index.php?c=batchoperation&m=run&tn=batchoperation_form'),
),"prefix"=>'batchoperation'
),
array('title'=>'BD管理',   'url'=>'',
'sublist'=>array(
array('title'=>'待认证列表','url'=>'/index.php?c=openuser&m=search&tn=openuser_wait&ou_status=0&order={"ou_complete":1}&search_page_id=1&search_page_size=10'),
array('title'=>'认证通过列表','url'=>'/index.php?c=openuser&m=search&tn=openuser_pass&ou_status=1&order={"ou_approve_time":1}&search_page_id=1&search_page_size=10'),
array('title'=>'认证失败列表','url'=>'/index.php?c=openuser&m=search&tn=openuser_fail&ou_status=2&order={"ou_approve_time":1}&search_page_id=1&search_page_size=10'),
array('title'=>'封禁账号列表','url'=>'/index.php?c=openuser&m=search&tn=openuser_forbid&ou_status=3&order={"ou_forbid_time":1}&search_page_id=1&search_page_size=10'),
),"prefix"=>'openuser'
),
);



//table fields
$config['table_fields']=array(
'quku_artists_base'=>array(
'ab_globalid',
'ab_name',
'ab_unique_name',
'ab_gender',
'ab_career',
'ab_info',
'ab_aliasname',
'ab_birthday',
'ab_translatename',
'ab_constellation',
'ab_stature',
'ab_weight',
'ab_bloodtype',
'ab_relatestars',
'ab_company',
'ab_area',
'ab_country',
'ab_synonym',
'ab_audit_status',
'ab_editusernow',
'ab_yyr_id',
//'ab_source_path'
),

'quku_songs_info'=>array(
'si_globalid',
'si_title',
'si_aliastitle',
"si_cluster_id",
'si_translatename',
'si_info',
'si_versions',
'si_styles',
'si_duration',
'si_album_no',
'si_synonym',
'si_album_id',
'si_album',
'si_proxycompany',
'si_trackid',
'si_isrc',
'si_isrc_flag',
'si_area',
'si_language',
'si_publishtime',
'si_cd_no',
'si_license_number',
'si_copyright_flag',
'si_recordingcopyright_type',
'si_recording_type',
'si_publishcompany',
'si_sub_publishcompany',
'si_prohibit_type',
'si_audit_status',
'si_audit_info',
'si_editusernow',
'si_pre_pubtime',
'si_relate_ids',
"si_distribution",
'si_yyr_id',
//'si_source_path'
),

'quku_albums_info'=>array(
'ai_globalid',
'ai_album',
'ai_aliasalbum',
'ai_translatename',
'ai_info',
'ai_language',
'ai_area',
'ai_duration',
'ai_version',
'ai_publishcompany',
'ai_sub_publishcompany',
'ai_publishtime',
'ai_songs_total',
'ai_styles',
'ai_productid',
'ai_productid_flag',
'ai_synonym',
'ai_audit_status',
'ai_audit_info',
'ai_source',
'ai_editusernow',
"ai_brief_info",
),
'quku_shows_news'=>array(
'sn_globalid',
'sn_title',
'sn_category',
'sn_city',
'sn_venue',
'sn_price',
'sn_info',
'sn_detailtime',
),
'quku_tag_dict'=>array(
'td_tagid',
'td_name',
'td_level',
'td_category',
'td_parentid',
),
'quku_options_dic'=>array(
'od_id',
'od_spell_code',
'od_category',
'od_type',
'od_word',
'od_remark',
),
"quku_mv_info" => array(
    'mi_globalid',
    'mi_title',
    'mi_subtitle',
    'mi_info',
    'mi_versions',
    'mi_label',
    'mi_area',
    'mi_proxycompany',
    'mi_publishcompany',
    'mi_publishtime',
    'mi_prodcompany',
    'mi_prohibit_type',
    'mi_pre_pubtime',
    ),
"quku_yingshi_info" => array(
    'yi_globalid',
    'yi_title',
    "yi_aliastitle",
    "yi_translatename",
    'yi_info',
    "yi_area",
    "yi_main",
    "yi_guest",
    "yi_director",
    "yi_session",
    "yi_language",
    "yi_type",
    "yi_label",
    'yi_versions',
    "yi_publishtime",
    ),
"quku_video_info" => array(
    'vi_globalid',
    'vi_mv_id',
    'vi_provider',
    ),
'quku_user_base'=>array(
'ub_id',
'ub_username',
'ub_groupid',
),
);

//get data from from
$config['get_formdata_map']=array(
'quku_artists_base'=>'getFormBaseData',
'quku_pic_info'=>'getFormPic',
'quku_relatively_links'=>'getFormRelativeLink',
'quku_songs_info'=>'getFormBaseData',
'quku_mv_info'=>'getFormBaseData',
'quku_yingshi_info'=>'getFormBaseData',
'quku_video_info'=>'getFormBaseData',
'quku_songs_files'=>'getFormMedia',
'quku_songs_lrcs'=>'getFormLrc',
'quku_songs_list'=>'getFormSonglist',
"quku_songs_clusters" => "getFormCluster",
'quku_mv_info'=>'getFormBaseData',
'quku_video_info'=>'getFormVideoFiles',
'quku_mv_ref'=>'getFormMvSong',
'quku_yingshi_ref'=>'getFormYingshiRef',
'quku_songs_copyright'=>'getFormCopyright',
'quku_artist_works_ref'=>'getFormAuthor',
'quku_albums_info'=>'getFormBaseData',
'quku_shows_news'=>'getFormBaseData',
'quku_tag_dict'=>'getFormBaseData',
'quku_tag_syn'=>'getFormTagsyn',
'quku_tag_info_rel'=>'getFormTagrel',
'quku_tag_info_rel1'=>'getFormTagrel1',
'quku_options_dic'=>'getFormBaseData',
'quku_user_base'=>'getFormBaseData',
);

$config['generate_formdata_map']=array(
'quku_artists_base'=>'generateFormBaseData',
'quku_pic_info'=>'generateFormPicData',
'quku_relatively_links'=>'generateFormRelativeLink',
'quku_songs_files'=>'generateFormMedia',
'quku_songs_lrcs'=>'generateFormLrc',
'quku_songs_copyright'=>'generateFormCopyright',
'quku_artist_works_ref'=>'generateFormAuthor',
'quku_songs_info'=>'generateFormBaseData',
'quku_mv_info'=>'generateFormBaseData',
'quku_yingshi_info'=>'generateFormBaseData',
'quku_video_info'=>'generateFormVideoFiles',
'quku_mv_ref'=>'generateFormMvSong',
'quku_yingshi_ref'=>'generateFormYingshiRef',
'quku_songs_list'=>'generateFormSonglist',
"quku_songs_clusters"=>"generateFormClusters",
'quku_albums_info'=>'generateFormBaseData',
'quku_shows_news'=>'generateFormBaseData',
'quku_tag_dict'=>'generateFormBaseData',
'quku_tag_syn'=>'generateFormTagsyn',
'quku_tag_info_rel'=>'generateFormTagrel',
'quku_tag_info_rel1'=>'generateFormTagrel1',
'quku_options_dic'=>'generateFormBaseData',
'quku_user_base'=>'generateFormBaseData',
'quku_open_user'=>'generateFormBaseData',
'quku_open_user_material'=>'generateFormUserMaterialData',
);

$config['form_structure']=array(
QUKU_TYPE_ARTIST=>array('quku_artists_base','quku_pic_info','quku_relatively_links','quku_tag_info_rel'),
QUKU_TYPE_SONG=>array('quku_songs_info','quku_pic_info','quku_songs_files','quku_songs_lrcs','quku_songs_copyright','quku_artist_works_ref','quku_tag_info_rel','quku_tag_info_rel1',"quku_songs_clusters"),
QUKU_TYPE_MV => array("quku_mv_info","quku_mv_ref","quku_video_info"/* ,"quku_video_files" */,"quku_artist_works_ref","quku_pic_info"),
QUKU_TYPE_YINGSHI => array("quku_yingshi_info","quku_yingshi_ref","quku_pic_info"),
QUKU_TYPE_ALBUM=>array('quku_albums_info','quku_artist_works_ref','quku_pic_info','quku_songs_list','quku_tag_info_rel'),
QUKU_TYPE_SHOW=>array('quku_shows_news','quku_artist_works_ref','quku_pic_info','quku_relatively_links'),
QUKU_TYPE_TAG=>array('quku_tag_dict','quku_tag_syn'),
QUKU_TYPE_OPTION=>array('quku_options_dic'),
QUKU_TYPE_USER=>array('quku_user_base'),
QUKU_TYPE_OPEN_USER=>array('quku_open_user','quku_open_user_material'),
);

$config['validate'] = array(
QUKU_TYPE_ARTIST=>array
(
array(
'field'=>'ab_name',
'label'   => '用户名',
'rules'   => 'required|max_length[100]'
),
array('field'=>'ab_unique_name',
'label'   => '唯一名',
'rules'   => 'required|max_length[100]'
),
array(
'field'=>'ab_gender',
'label'   => '性别',
'rules'   => 'required'
),
array(
'field'=>'ab_career',
'label'   => '职业',
'rules'   => 'required|max_length[100]'
),
array(
'field'=>'ab_area',
'label'   => '地区',
'rules'   => 'required'
),
array(
'field'=>'ab_info',
'label'   => '简介',
'rules'   => 'max_length[65535]'
),
array(
'field'=>'ab_aliasname',
'label'   => '别名',
'rules'   => 'max_length[100]'
),
array(
'field'=>'ab_translatename',
'label'   => '译名',
'rules'   => 'max_length[100]'
),
array(
'field'=>'ab_relatestars',
'label'   => '相关明星',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ab_company',
'label'   => '所属公司',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ab_country',
'label'   => '国家',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ab_synonym',
'label'   => '同义词',
'rules'   => 'max_length[100]'
),
array(
'field'=>'ab_source_path',
'label'   => '来源路径',
'rules'   => 'max_length[100]'
),
),
QUKU_TYPE_SONG=>array(
array(
'field'=>'si_title',
'label'   => '歌曲名',
'rules'   => 'required|max_length[1024]'
),
array(
'field'=>'si_aliastitle',
'label'   => '别名',
'rules'   => 'max_length[100]'
),
array(
'field'=>'si_translatename',
'label'   => '译名',
'rules'   => 'max_length[100]'
),
array(
'field'=>'si_info',
'label'   => '描述',
'rules'   => 'max_length[200]'
),
array(
'field'=>'si_versions',
'label'   => '版本',
'rules'   => 'max_length[32]'
),
array(
'field'=>'si_styles',
'label'   => '曲风',
'rules'   => 'max_length[200]'
),
array(
'field'=>'si_synonym',
'label'   => '同义词',
'rules'   => 'max_length[100]'
),
array(
'field'=>'si_album',
'label'   => '专辑名',
'rules'   => 'max_length[1024]'
),
array(
'field'=>'si_proxycompany',
'label'   => '付费公司',
'rules'   => 'required|max_length[200]'
),
array(
'field'=>'si_trackid',
'label'   => '专辑名',
'rules'   => 'max_length[15]'
),
array(
'field'=>'si_isrc',
'label'   => 'isrc',
'rules'   => 'max_length[50]'
),
array(
'field'=>'si_language',
'label'   => '语言',
'rules'   => 'max_length[200]'
),
array(
'field'=>'si_license_number',
'label'   => '批准文号',
'rules'   => 'max_length[100]'
),
array(
'field'=>'si_publishcompany',
'label'   => '发行公司',
'rules'   => 'required|max_length[200]'
),
array(
'field'=>'si_sub_publishcompany',
'label'   => '厂牌公司',
'rules'   => 'max_length[200]'
),
array(
'field'=>'si_prohibit_type',
'label'   => '屏蔽类型',
'rules'   => 'required|max_length[3]'
),
array(
'field'=>'quku_artist_works_ref',
'label'   => '歌手名',
'rules'   => 'required'
),
),
QUKU_TYPE_ALBUM=>array(
array(
'field'=>'ai_album',
'label'   => '专辑名',
'rules'   => 'required|max_length[1024]'
),
array(
'field'=>'ai_area',
'label'   => '发行地区',
'rules'   => 'required'
),
array(
'field'=>'ai_publishcompany',
'label'   => '发行公司',
'rules'   => 'required|max_length[200]'
),
array(
'field'=>'quku_pic_info',
'label'   => '海报',
'rules'   => 'required'
),
array(
'field'=>'ai_aliasalbum',
'label'   => '别名',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ai_translatename',
'label'   => '译名',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ai_info',
'label'   => '简介',
'rules'   => 'max_length[65535]'
),
array(
'field'=>'ai_language',
'label'   => '语言',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ai_duration',
'label'   => '时长',
'rules'   => 'max_length[10]'
),
array(
'field'=>'ai_sub_publishcompany',
'label'   => '厂牌公司',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ai_styles',
'label'   => '曲风',
'rules'   => 'max_length[200]'
),
array(
'field'=>'ai_productid',
'label'   => '产品号',
'rules'   => 'max_length[40]'
),
array(
'field'=>'ai_styles',
'label'   => '曲风',
'rules'   => 'max_length[100]'
),
array(
'field'=>'ai_synonym',
'label'   => '同义词',
'rules'   => 'max_length[100]'
),
array(
'field'=>'quku_artist_works_ref',
'label'   => '歌手名',
'rules'   => 'required'
),
array(
'field'=>'quku_pic_info',
'label'   => '图片',
'rules'   => 'required'
),
),
QUKU_TYPE_MV => array(
    array(
	'field'=>'mi_title',
	'label'   => 'MV名',
	'rules'   => 'required|max_length[1024]'
	),
    array(
	'field'=>'quku_artist_works_ref',
	'label'   => '歌手名',
	'rules'   => 'required'
	),
    array(
	'field'=>'mi_subtitle',
	'label'   => 'MV副标题',
	'rules'   => 'required'
	),
    array(
	'field'=>'mi_label',
	'label'   => '标签',
	'rules'   => 'required'
	),
    array(
	'field'=>'mi_versions',
	'label'   => ' 版本',
	'rules'   => 'required'
	),

    ),
QUKU_TYPE_YINGSHI => array(
    array(
	'field'=>'yi_title',
	'label'   => '影视名称',
	'rules'   => 'required|max_length[1024]'
	),
    array(
	'field'=>'yi_type',
	'label'   => '影视类型',
	'rules'   => 'required|max_length[1024]'
	),

    ),
QUKU_TYPE_SHOW=>array(
array(
'field'=>'sn_title',
'label'   => '演出名',
'rules'   => 'required|max_length[100]'
),
array(
'field'=>'sn_category',
'label'   => '类别',
'rules'   => 'required'
),
array(
'field'=>'sn_city',
'label'   => '城市',
'rules'   => 'required'
),
array(
'field'=>'sn_venue',
'label'   => '场馆',
'rules'   => 'required'
),
array(
'field'=>'sn_price',
'label'   => '票价',
'rules'   => 'max_length[100]'
),
array(
'field'=>'sn_info',
'label'   => '简介',
'rules'   => 'required|max_length[65535]'
),
array(
'field'=>'sn_detailtime',
'label'   => '演出时间',
'rules'   => 'required|max_length[200]'
),
array(
'field'=>'quku_pic_info',
'label'   => '图片',
'rules'   => 'required'
),
),
QUKU_TYPE_TAG=>array(
array(
'field'=>'td_name',
'label'   => '标签名',
'rules'   => 'required|max_length[50]'
),
array(
'field'=>'td_level',
'label'   => '级别',
'rules'   => 'required'
),
array(
'field'=>'td_category',
'label'   => '类别',
'rules'   => 'required'
),
),
QUKU_TYPE_OPTION=>array(
array(
'field'=>'od_spell_code',
'label'   => '拼音码',
'rules'   => 'required|max_length[100]'
),
array(
'field'=>'od_category',
'label'   => '配置类型',
'rules'   => 'required|max_length[50]'
),
array(
'field'=>'od_type',
'label'   => '信息类型',
'rules'   => 'required'
),
array(
'field'=>'od_word',
'label'   => '单词',
'rules'   => 'required|max_length[100]'
),
array(
'field'=>'od_remark',
'label'   => '备注',
'rules'   => 'max_length[100]'
),
),
QUKU_TYPE_USER=>array(
array(
'field'=>'ub_username',
'label'   => '用户名',
'rules'   => 'required|max_length[100]'
),
array(
'field'=>'ub_username',
'label'   => '用户名',
'rules'   => 'required|max_length[32]'
),
array(
'field'=>'ub_groupid',
'label'   => '用户组',
'rules'   => 'required'
),
),

QUKU_TYPE_PIC=>array(
'size'=>1024*1024*100,
'type'=>array('image/jpeg','image/png','image/gif','image/pjpeg','image/x-png','application/octet-stream'),
),
QUKU_TYPE_MEDIA=>array(
'size'=>1024*1024*200,
'type'=>array('audio/mpeg','application/octet-stream','audio/mp3','audio/m4a','audio/wav','audio/x-wav'),
),
QUKU_TYPE_LRC=>array(
'size'=>1024*1024*100,
'type'=>array('application/octet-stream','text/plain', 'application/lrc'),
),
);

//$config['form_unmatch_field']=array(
//QUKU_TYPE_ARTIST=>array('ab_career'),
//QUKU_TYPE_ALBUM=>array());
$config['pic_compress_size']=array(QUKU_TYPE_ARTIST=>array('300','240','180','150','130','120','90','60','40','30'),QUKU_TYPE_ALBUM=>array('300','240','180','150','130','120','90','60','40','30'),QUKU_TYPE_SONG=>array('300','240','180','150','130','120','90','60','40','30'),QUKU_TYPE_SHOW=>array(),QUKU_TYPE_MV => array());
$config['temp_path']='/tmp/';
$config['form_option']=array(
QUKU_TYPE_ARTIST=>array(
'ab_gender'=>array(0=>'未知',1=>'男',2=>'女',3=>'组合',4=>'乐队'),
'ab_constellation'=>array(
0=>'未知',
1=>'白羊座',
2=>'金牛座',
3=>'双子座',
4=>'巨蟹座',
5=>'狮子座',
6=>'处女座',
7=>'天秤座',
8=>'天蝎座',
9=>'射手座',
10=>'摩羯座',
11=>'水瓶座',
12=>'双鱼座',
),
'ab_career'=>array(
'歌手'=>'歌手',
'演员'=>'演员',
'主持'=>'主持',
'模特'=>'模特',
'导演'=>'导演',
'制片'=>'制片',
'作词'=>'作词',
'作曲'=>'作曲',
'演奏家'=>'演奏家',
'指挥家'=>'指挥家',
'制作人'=>'制作人',
'其它'=>'其它',
),
'ab_area'=>array(0=>'未知',5=>'其它',1=>'内地',2=>'港台',3=>'欧美',4=>'日韩',6=>"日本",7=>"韩国"),
'ab_bloodtype'=>array(0=>'未知',	1=>'A型',2=>'B型',3=>'AB型',4=>'O型')
,
),
QUKU_TYPE_SONG=>array(
'si_versions'=>array('现场'=>'现场',
'伴奏/纯音乐'=>'伴奏/纯音乐',
'混音'=>'混音',
'小样儿'=>'小样儿',
'不插电'=>'不插电',
'片段'=>'片段',
'翻唱'=>'翻唱',
'铃声'=>'铃声',
'对白'=>'对白',
'电台版'=>'电台版',
'抢听版'=>'抢听版'
),
'si_styles'=>array(
'影视原声'=>'影视原声',
'流行'=>'流行',
'摇滚'=>'摇滚',
'嘻哈'=>'嘻哈',
'轻音乐'=>'轻音乐',
'爵士'=>'爵士',
'古典'=>'古典',
'世界音乐'=>'世界音乐',
'R&B'=>'R&B',
'雷鬼'=>'雷鬼',
'布鲁斯'=>'布鲁斯',
'民谣'=>'民谣',
'电子'=>'电子',
'民族'=>'民族',
'乡村'=>'乡村',
'其他'=>'其他',
),
"sf_usage_flag" =>array('0' => "常规",'3' => "合成歌曲",'4' => '原唱歌曲','5' => '伴奏音频'),
'si_area'=>array(0=>'未知',5=>'其它',1=>'内地',2=>'港台',3=>'欧美',4=>'日韩',6=>"日本",7=>"韩国"),
'si_recordingcopyright_type'=>array(
1=>'全部', 2=>'仅下载权',3=>'仅播放权'
),
"recording_type" => array(
			  "product"=>2,
			  "types"=>2,
			  ),
"si_recording_type"=>array(
			  "1110"=>"WEB端播放权",
			  "1101"=>"WEB端下载权",
			  "1011"=>"无线端播放权",
			  "0111"=>"无线端下载权",
),
'si_isrc_flag'=>array(
0=>'自动生成isrc',
1=>'唱片公司提供isrc'),
/* "si_tag_rel" => array( */
/* 		      1=>"流行", */
/* 		      3=>"摇滚", */
/* 		      1371732=>"民谣/乡村", */
/* 		      6=>"爵士", */
/* 		      2=>"电子", */
/* 		      1371749=>"世界音乐/新世纪", */
/* 		      8=>"轻音乐", */   
/* 		      9=>"古典", */
/* 		      10=>"宗教", */
/* 		      14=>"曲艺", */
/* 			      ), */
/* "si_tag_rel1"=>array( */
/* 		     1=>array(53=>"迪斯科",46=>"嘻哈",1371727=>"流行舞曲",1343133=>"另类流行",60=>"独立流行",76=>"节奏布鲁斯",1371728=>"灵魂乐",5=>"蓝调",1371750=>"放克",1371751=>"中文流行",1371752=>"粤语流行",1371729=>"韩国流行",1371730=>"日本流行",1371731=>"拉丁流行",1371753=>"法国香颂",11=>"雷鬼"), */
/* 		     3=>array(697072=>"英伦摇滚",1371754=>"日系摇滚",114=>"朋克",1371755=>"情绪摇滚",654=>"硬核",488433=>"华丽摇滚",137=>"视觉摇滚",116=>"硬摇滚",117=>"软摇滚",118=>"工业音乐",119=>"乡村摇滚",120=>"哥特",121=>"金属",122=>"车库",700930=>"垃圾摇滚",123=>"后摇",528075=>"后朋克",128=>"独立摇滚",126=>"艺术摇滚",129=>"新浪潮",130=>"前卫摇滚",136=>"山区乡村摇滚",1371756=>"自赏",1371757=>"迷幻",131=>"太空摇滚",1358176=>"另类摇滚",1363966=>"实验音乐"), */
/* 		     1371732=>array(4=>"民谣",144=>"乡村",479237=>"城市民谣",145=>"蓝草",1371733=>"原音不插电",1371734=>"叙事歌谣",1371735=>"凯尔特",146=>"牛仔",152=>"法朵"), */
/* 		     6=>array(161=>"融合爵士",1363897=>"波普",165=>"大乐团",1363787=>"摇摆乐",1371737=>"布吉乌吉",1371738=>"酸爵士",1364139=>"冷爵士",1371740=>"波萨诺瓦"), */
/*                      2=>array(1363944=>"豪斯舞曲",1371741=>"驰放",91=>"氛围",1371742=>"神游舞曲",1371791=>"鼓打贝斯",94=>"智能舞曲",1371744=>"科技舞曲",1371745=>"迷幻舞曲",99=>"大节拍"), */
/*                     1371749=>array(7=>"世界音乐",1371758=>"中国民歌",1371759=>"中国民乐",1371760=>"日本传统音乐",1371761=>"非洲传统音乐",1371762=>"巴西传统音乐",1371763=>"印度传统音乐",1371764=>"中东传统音乐",1371765=>"俄罗斯传统音乐",1371766=>"南美洲传统音乐",1151118=>"新世纪",478372=>"新古典"), */
/* 		     8=>array(1371767=>"纯器乐",1371768=>"沙发音乐"), */
/* 		     9=>array(1371769=>"跨界",1371770=>"电影配乐",1371771=>"歌剧",1345289=>"音乐剧",1371772=>"交响乐",1371773=>"管弦乐",1371774=>"大合唱",1371775=>"声乐"), */
/*                      10=>array(1371776=>"基督音乐",1371777=>"福音音乐",479555=>"佛教音乐",1371778=>"印度教音乐",1371779=>"清真教音乐"), */
/* 		     14=>array(479576=>"京剧",1371784=>"京韵大鼓/京东大鼓",1371780=>"二人转",478193=>"黄梅戏",1371785=>"凤阳花鼓",1371781=>"相声",1371782=>"小品",498046=>"快板",1371783=>"评书"), */

/* ),*/

'si_prohibit_type'=>array(
0=>'有版权',
1=>'白名单',
2=>'灰名单',
/* 3=>'黑名单', */
4=>'屏蔽名单',
),
'si_prohibit_info'=>array(
0=>'',
1=>'Default：命中文化部黑名单，或者被文化部通报等',
2=>'Default：版权到期等',
3=>'Default：命中敏感词黑名单，黄反信息等',
),
"si_audit_status" => array(
    "0" => "已审核",
    "1" => "未审核",
    "2" => "审核失败",
    ),
"si_audit_info" => array(
    "授权书和实际数据不符" => "授权书和实际数据不符",
    "音频无法播放" => "音频无法播放",
    )
),
QUKU_TYPE_ALBUM=>array(
'ai_area'=>array(
     0=>'未知',5=>'其它',1=>'内地',2=>'港台',3=>'欧美',4=>'日韩',6=>"日本",7=>"韩国"
),
'ai_version'=>array(0=>'未知',1=>'专辑',2=>'单曲',3=>'EP',4=>'Live演唱会'),
'ai_styles'=>array(
'影视原声'=>'影视原声',
'流行'=>'流行',
'摇滚'=>'摇滚',
'嘻哈'=>'嘻哈',
'轻音乐'=>'轻音乐',
'爵士'=>'爵士',
'古典'=>'古典',
'世界音乐'=>'世界音乐',
'R&B'=>'R&B',
'雷鬼'=>'雷鬼',
'布鲁斯'=>'布鲁斯',
'民谣'=>'民谣',
'电子'=>'电子',
'民族'=>'民族',
'乡村'=>'乡村',
'其他'=>'其他',
),
'ai_source'=>array(
0=>'未知',
1=>'mis',
2=>'OneStop',
3=>'EMI',
4=>'top100.cn',
5=>'qq.com',
6=>'local_30w',
7=>'soso.com',
8=>'EEG',
9=>'mp3self',
10=>'rock',
11=>'pocket',
12=>'songjin',
13=>'9imusic',
14=>'yaying',
15=>'jingwen',
),
'ai_productid_flag'=>array(
0=>'自动生成productid',
1=>'唱片公司提供productid'),
"ai_audit_status" => array(
    "0" => "已审核",
    "1" => "未审核",
    "2" => "审核失败",
    ),
"ai_audit_info" => array(
    "授权书和实际数据不符" => "授权书和实际数据不符",
    "专辑名不规范" => "专辑名不规范",
    )
),
QUKU_TYPE_SHOW=>array(
'sn_category'=>array(
0=>'未知',
1=>'演唱会',
2=>'颁奖礼',
3=>'电影节',
4=>'音乐节',
5=>'歌友会',
6=>'首映式',
7=>'发布会',
8=>'签售会',
9=>'媒体通告',
10=>'话剧歌剧',
11=>'音乐会',
12=>'戏曲综艺',
13=>'舞蹈芭蕾',
14=>'体育比赛',
15=>'度假休闲',
16=>'周边商品',
),
'sn_city'=>array(
0=>'未知',
1=>'北京市',
2=>'天津市',
3=>'沈阳市',
4=>'大连市',
5=>'哈尔滨市',
6=>'济南市',
7=>'青岛市',
8=>'南京市',
9=>'上海市',
10=>'杭州市',
11=>'武汉市',
12=>'广州市',
13=>'深圳市',
14=>'重庆市',
15=>'成都市',
16=>'西安市',
17=>'石家庄市',
18=>'长春市',
19=>'呼和浩特市',
20=>'太原市',
21=>'郑州市',
22=>'合肥市',
23=>'无锡市',
24=>'苏州市',
25=>'宁波市',
26=>'福州市',
27=>'厦门市',
28=>'南昌市',
29=>'长沙市',
30=>'汕头市',
31=>'珠海市',
32=>'海口市',
33=>'三亚市',
34=>'南宁市',
35=>'贵阳市',
36=>'昆明市',
37=>'香港',
38=>'澳门',
39=>'台湾'
),
),
QUKU_TYPE_TAG=>array(
'td_level'=>array(1=>'一级',2=>'二级',3=>'三级'),
'td_category'=>array(0=>'其他',1=>'曲风',2=>'颜色',3=>'心情感受',4=>'使用情境',5=>"年代",6=>"主题",7=>"乐器音色",8=>"语言&地域",9=>"风格"),
),
QUKU_TYPE_OPTION=>array(
'od_type'=>array(QUKU_TYPE_ARTIST=>'明星',QUKU_TYPE_ALBUM=>'专辑',QUKU_TYPE_SONG=>'单曲',QUKU_TYPE_SHOW=>'演出'),
'od_category'=>array(1=>'国家',2=>'语言',3=>'付费公司',4=>'发行公司',5=>'制作公司',6=>'厂牌公司',7=>'著作权公司'),
),
QUKU_TYPE_USER=>array(
'ub_groupid'=>array(1=>'外包编辑',2=>'正式编辑',3=>'管理员',4=>'BD管理账号')
),
QUKU_TYPE_MV => array(
    'mi_area'=>array(0=>'未知',5=>'其它',1=>'内地',2=>'港台',3=>'欧美',4=>'日韩',5=>"其他",6=>"日本",7=>"韩国"),
    'mi_prohibit_type'=>array(0=>'有版权',1=>'白名单',2=>'灰名单',4=>'屏蔽名单',100=>"未处理"),
    "vi_provider" => array("11" => "爱奇艺","12"=>"音悦台"),
    "vf_file_extension" => array("swf" => "swf","mp4"=>"mp4"),
    "vf_definition" => array("11"=>"极速","21"=>"普清","31"=>"标清","41"=>"高清","51"=>"超清"),
    "mi_versions" => array("官方版"=>"官方版","现场版"=>"现场版","演唱会版"=>"演唱会版","饭团版"=>"饭团版","字幕版"=>"字幕版","竖屏版"=>"竖屏版"),
    ),
QUKU_TYPE_YINGSHI => array(
    'yi_area'=>array(0=>'未知',5=>'其它',1=>'内地',2=>'港台',3=>'欧美',4=>'日韩',5=>"其他",6=>"日本",7=>"韩国"),
    /* "yi_versions" => array("官方版"=>"官方版","现场版"=>"现场版","演唱会版"=>"演唱会版","饭团版"=>"饭团版","字幕版"=>"字幕版","竖屏版"=>"竖屏版"), */
    "yi_type" => array("0"=>"未知","1"=>"电影","2"=>"电视剧","3"=>"动漫","4"=>"综艺","5"=>"纪录片","6"=>"广告","7"=>"游戏"),
    "yr_ref_type" => array("0"=>"未知","1"=>"单曲","101"=>"人工关联单曲","2"=>"专辑","102"=>"人工关联专辑"),
    "yr_content_type_1" => array("0"=>"未知","1"=>"主题曲","2"=>"片头曲","3"=>"插曲","4"=>"片尾曲","5"=>"选秀"),
    "yr_content_type_2" => array("0"=>"未知","1"=>"影视原声"),
    ),
QUKU_TYPE_BATCHOPERATION => array(
"st_field"=>array(
	"quku_songs_info"=> array(
		"awr_artist_name"=>"明星名",
		"si_status" => "发布状态",
		"si_delflag" => "删除状态",
		"si_versions" => "版本",
		"si_publishcompany" => "发行公司",
		"si_proxycompany" => "付费公司",
		"si_charge"	  => "收费状态",
		"si_prohibit_type" => "版权状态",
		"si_publishtime"   => "发布时间",
		"si_distribution"   => "多端分发状态",
		"si_recordingcopyright_type" => "录音版权",
		/* "si_recording_type" => "多端分发版权", */
		"si_audit_status" => "审核状态",
		"si_edituser" => "最后编辑人",
	),
	"quku_albums_info" => array(
			   "awr_artist_name" => "明星名",
			   "ai_publishcompany" => "发行公司",
			   "ai_area" => "发行地区",
			   "ai_status"	       => "发布状态",
			   "ai_delflag"	       => "删除状态",
	),

),
"st_replace_field" => array(
	"quku_songs_info"=> array(
		"si_title" => "歌曲名",
		"awr_artist_name"=>"明星名",
		"si_versions" => "版本",
		"si_styles" => "风格",
		"si_language" => "语言",
		"si_isrc" => "isrc",
		"si_publishcompany" => "发行公司",
		"si_publishtime" => "发行时间",
		"si_prohibit_type" => "版权标识",
		"si_proxycompany" => "付费公司",
		"si_charge"	  => "收费状态",
		"si_audio"       =>"音频",
		"si_lyric"       =>"歌词",
		"si_copyright"   => "词曲版权",
		"si_edituser" => "最后编辑人",
	),
	"quku_albums_info" => array(
			   "ai_album"=>"专辑名",
			   "awr_artist_name" => "明星名",
			   "ai_version"=>"版本",
			   "ai_styles" => "风格",
			   "ai_language" => "语言",
			   "ai_productid" => "产品号",
			   "ai_publishcompany" => "发行公司",
			   "ai_publishtime"=>"发行时间",
			   "ai_picture"	       => "专辑图片",
	),
),
"st_tables" => array("quku_songs_info" => "单曲表","quku_albums_info"=>"专辑表"),
"st_task" => array("db"=>"更新db","rollback"=>"回滚","prohibit"=>"修改白名单","replace"=>"替换","auto"=>"手动修改单曲","auto_album"=>"手工修改专辑"),
"st_url" => QUKU_BATCHOPERATION_URL,
),

QUKU_TYPE_SEARCH=>array(
    "main_tables" => array(
	"quku_albums_info" => array(
	    "name" => "专辑表",
	    "value" => "quku_albums_info",
	    "fields" => array(
		"ai_globalid" => "专辑ID",
		"ai_album" => "专辑名",
		"ai_language" => "专辑语言",
		"ai_area" => "专辑地区",
		"ai_version" => "专辑版本",
		"ai_publishcompany" => "专辑发行公司",
		"ai_publishtime" => "专辑发行时间",
		"ai_productid" => "专辑产品号",
		"ai_source" => "专辑来源",
		"ai_jointime" => "专辑入库时间",
		"ai_edituser" => "专辑最后修改人",
		"ai_status" => "专辑发布状态",
		"ai_audit_status" => "专辑审核状态",
		"ai_delflag"=>"专辑删除状态",
		),
	    "relations" => array(
		"quku_songs_info" => array(
		    "name" => "歌曲表",
		    "value" => "quku_songs_info",
		    "fields" => array(
			'si_globalid'=>'歌曲ID',
			'si_title'=>'歌曲名',
			'si_publishcompany'=>'歌曲发行公司',
			'si_proxycompany'=>'歌曲付费公司',
			'si_album'=>'歌曲专辑名',
			'si_publishtime'=>'歌曲发行时间',
			'si_styles'=>'歌曲风格',
			'si_versions'=>'歌曲版本',
			'si_area'=>'歌曲发行地区',
			'si_language'=>'歌曲语言',
			'si_isrc'=>'歌曲ISRC号',
			"si_source" => "歌曲来源",
			'si_jointime'=>'歌曲上传时间',
			'si_prohibit_type'=>'歌曲屏蔽类型',
			'si_edittime'=>'歌曲最后修改时间',
			'si_source'=>'歌曲来源',
			'si_status'=>'歌曲发布状态',
			'si_audit_status'=>'歌曲审核状态',
			'si_delflag'=>'歌曲删除状态',
			)
 		    ),
		"quku_artist_works_ref"=>array(
		    "name" => "歌手作品表",
		    "value" => "quku_artist_works_ref",
		    "fields" => array(
			"awr_artist_name" => "明星名",
			"awr_artist_id" => "明星ID",
			),
		    ),
		"quku_pic_info" => array(
		    "name" => "图片表",
		    "value" => "quku_pic_info",
		    'fields' => array(
			"pi_pic_width" => "图片宽度",
			"pi_pic_height" => "图片高度",
			"pi_link" => "图片链接",
			"pi_jointime" => "图片入库时间"
			),
		    ),
		),
	    ),
	"quku_artists_base" => array(
	    "name" => "明星表",
	    "value" => "quku_artists_base",
	    "fields" => array(
		"ab_globalid" => "明星ID",
		"ab_name" => "明星名",
		"ab_unique_name" => "明星唯一名",
		"ab_gender" => "明星性别",
		"ab_area" => "明星地区",
		"ab_synonym" => "明星同义词",
		"ab_source" => "明星来源",
		"ab_jointime" => "明星入库时间",
		"ab_status" => "明星发布状态",
		"ab_delflag" => "明星删除状态",
		"ab_audit_status" => "明星审核状态",
		),
	    "relations" => array(
		"quku_artist_works_ref" => array(
		    "name" => "明星作品表",
		    "value" => "quku_artist_works_ref",
		    "fields" => array(
			"awr_type" => "信息类型",
			"awr_artist_order" => "展现次序",
			),
		    ),
		"quku_pic_info" => array(
		    "name" => "图片表",
		    "value" => "quku_pic_info",
		    'fields' => array(
			"pi_pic_width" => "图片宽度",
			"pi_pic_height" => "图片高度",
			"pi_link" => "图片链接",
			"pi_jointime" => "图片入库时间"
			),
		    ),
		),
	    ),
	"quku_songs_info" => array(
	    "name" => "歌曲表",
	    "value" => "quku_songs_info",
	    "fields"=> array(
		'si_globalid'=>'歌曲ID',
		'si_title'=>'歌曲名',
		'si_publishcompany'=>'歌曲发行公司',
		'si_proxycompany'=>'歌曲付费公司',
		'si_album'=>'歌曲专辑名',
		'si_publishtime'=>'歌曲发行时间',
		'si_styles'=>'歌曲风格',
		'si_versions'=>'歌曲版本',
		'si_area'=>'歌曲发行地区',
		'si_language'=>'歌曲语言',
		'si_isrc'=>'歌曲ISRC号',
		"si_source" => "歌曲来源",
		'si_jointime'=>'歌曲上传时间',
		'si_prohibit_type'=>'歌曲屏蔽类型',
		'si_edittime'=>'歌曲最后修改时间',
		'si_source'=>'歌曲来源',
		'si_status'=>'歌曲发布状态',
		'si_audit_status'=>'歌曲审核状态',
		'si_delflag'=>'歌曲删除状态',
		),
	    "relations" => array(
		"quku_artist_works_ref"=>array(
		    "name" => "歌手作品表",
		    "value" => "quku_artist_works_ref",
		    "fields" => array(
			"group_concat(distinct awr_artist_name)" => "明星名",
			"group_concat(distinct awr_artist_id)" => "明星ID",
			),
		    ),
		"quku_songs_files" => array(
		    "name" => "歌曲音频表",
		    "value" => "quku_songs_files",
		    "fields" => array(
			'sf_globalid'=>'音频ID',
			'sf_file_bitrate'=>'音频码率',
			'sf_file_extension'=>'音频格式',
			"sf_fpid" => "指纹ID",
			"sf_jointime"=>"音频入库时间",
            "sf_file_link"=>"音频下载连接",
            "sf_md5"=>"音频md5",
			),
		    ),
		"quku_songs_copyright" => array(
		    "name"=>"歌曲版权表",
		    "value" => "quku_songs_copyright",
		    "fields" => array(
			"sc_artist_name" => "做词/曲人名称",
			"sc_company" => "公司",
			"sc_percent" => "百分比",
			"sc_type" => "版权类型(1作曲，2作词)",
			),
		    ),
		"quku_songs_lrcs" => array(
		    "name" => "歌词表",
		    "value" => "quku_songs_lrcs",
		    "fields" => array(
			"sl_lyrics" => "歌词内容",
			),
		    ),
		"quku_tag_info_ref" => array(
		    "name" => "标签表",
		    "value" => "quku_tag_info_ref",
		    "fields" => array(
			"ti_weight" => "权重",
			"ti_rawweight" => "基础权重",
			),
		    ),
		),
	    )
	),
    'st_needpv'=>array('0'=>'不使用pv','1'=>'pv排序'),
    "st_task" => array("db"=>"查询db","title"=>"title重复","fpid"=>"fpid重复"),
    'st_symbol'=>array(
	'='=>'=',
	'>'=>'>',
	'>='=>'>=',
	'<'=>'<',
	'<='=>'<=',
	'!='=>'!=',
	"in" =>"in",
	'LIKE'=>'LIKE',
	'LIKE%...%'=>'LIKE%...%',),

    "st_url" => QUKU_STATISTICS_URL,
    ),
);

$config['dic_option']=array(
QUKU_TYPE_ARTIST=>array(
'ab_country'=>array('category'=>1),
),
QUKU_TYPE_SONG=>array(
'si_language'=>array('category'=>2,'option_flag'=>true),
'si_publishcompany'=>array('category'=>4,"need_split"=>false),
//'si_sub_publishcompany'=>array('category'=>6),
'si_proxycompany'=>array('category'=>3),
//'sc_company'=>array('category'=>'著作权公司','table'=>'quku_songs_copyright'),
),
QUKU_TYPE_ALBUM=>array(
'ai_language'=>array('category'=>2,'option_flag'=>true,'type'=>QUKU_TYPE_SONG),
'ai_publishcompany'=>array('category'=>4,'option_flag'=>true,'type'=>QUKU_TYPE_SONG,"need_split"=>false),
//'ai_sub_publishcompany'=>array('category'=>6,'option_flag'=>true,'type'=>QUKU_TYPE_SONG),
),
QUKU_TYPE_SHOW=>array(),
QUKU_TYPE_TAG=>array(),
QUKU_TYPE_OPTION=>array(),
QUKU_TYPE_USER=>array(),
QUKU_TYPE_MV => array(),
QUKU_TYPE_YINGSHI => array(
    'yi_language'=>array('category'=>2,'option_flag'=>true,"type"=>1),
    ),
);

$config['copyright']=array('quku_songs_copyright_compose'=>1,'quku_songs_copyright_writing'=>2);

$config['search_option']=array(
	'common'=>array(
	'search_scend'=>array('option'=>array(QUKU_OPTIONS_DEASCEND=>'降序',QUKU_OPTIONS_ASCEND=>'升序'),'default'=>QUKU_OPTIONS_DEASCEND),
	'search_match'=>array('option'=>array(0=>'精确匹配',1=>'只匹配左边',2=>'模糊匹配'),'default'=>0),
	'search_page_size'=>array('option'=>array(10=>10,20=>20,30=>30,50=>50,100=>100),'default'=>20),
	'search_count'=>array('option'=>array(1=>'统计总数',0=>'不统计总数'),'default'=>0),
	),
	QUKU_TYPE_ARTIST=>array(
	'search_field'=>array('option'=>array('ab_name'=>'明星名','ab_globalid' => '明星ID', 'ab_joinuser'=>'创建人','ab_edituser'=>'最后修改人','td_name'=>'标签名'),'default'=>'ab_name'),
	'search_order'=>array('option'=>array('ab_edittime'=>'最后修改时间','ab_jointime'=>'创建时间', 'ab_name' => '明星名'),'default'=>'ab_edittime','convert'=>array('ab_name')),
	'search_time'=>array('option'=>array('ab_edittime'=>'最后修改时间'),'default'=>'ab_edittime'),
	'search_audit_status'=>array('option'=>array(2=>'全部',0=>'已审核',1=>'未审核'),'default'=>2),
	'search_delflag'=>array('option'=>array(0=>'未删除',1=>'已删除',2=>'全部'),'default'=>0),
	'search_status'=>array('option'=>array(2=>'全部',0=>'已发布',1=>'未发布'),'default'=>2),
	),
	QUKU_TYPE_SONG=>array(
	    'search_field'=>array('option'=>array('si_title'=>'歌曲名','si_globalid' => '歌曲id','si_publishcompany'=>'发行公司','si_album'=>'专辑名','awr_artist_name'=>'明星名', 'si_joinuser'=>'创建人','si_edituser'=>'最后修改人','si_cluster_id'=>"歌曲簇ID",'sf_globalid'=>'音频id','sf_fpid'=>'指纹id','sf_usage_flag'=>'音频用途', 'td_name'=>'标签名','si_isrc'=>'ISRC','si_source'=>'来源(开放平台=1000)'),'default'=>'si_title'),
	'search_field2'=>array('option'=>array('awr_artist_name'=>'明星名', 'si_joinuser'=>'创建人','si_edituser'=>'最后修改人','si_album'=>'专辑名','si_publishcompany'=>'发行公司'),'default'=>'awr_artist_name'),
	'search_order'=>array('option'=>array('si_edittime'=>'最后修改时间','si_jointime'=>'创建时间','si_publishtime'=>'发行时间', 'si_album' => '专辑名','si_publishcompany'=>'发行公司',),'default'=>'si_edittime','convert'=>array('si_album','si_publishcompany')),
	'search_time'=>array('option'=>array('si_edittime'=>'最后修改时间'),'default'=>'si_edittime'),
	'search_audit_status'=>array('option'=>array(2=>'全部',0=>'已审核',1=>'未审核'),'default'=>2),
	'search_delflag'=>array('option'=>array(0=>'未删除',1=>'已删除',2=>'全部'),'default'=>0),
	'search_status'=>array('option'=>array(2=>'全部',0=>'已发布',1=>'未发布'),'default'=>2),
	'search_prohibit'=>array('option'=>array(5=>'全部',0=>'有版权',1=>'白名单',2=>'灰名单',3=>'黑名单',4=>'屏蔽名单'),'default'=>5),
	),
	QUKU_TYPE_MV=>array(
	    'search_field'=>array('option'=>array('mi_title'=>'标题','mi_globalid' => 'MV ID',"mr_itemid" => "歌曲id","vi_source_path"=>"链接",'awr_artist_name'=>'明星名',"mi_subtitme"=>"副标题", 'mi_joinuser'=>'创建人','mi_edituser'=>'最后修改人'),'default'=>'mi_title'),
	    'search_field2'=>array('option'=>array('awr_artist_name'=>'明星名','mi_edituser'=>'最后修改人','mi_joinuser'=>'创建人'),'default'=>'awr_artist_name'),
	    'search_order'=>array('option'=>array('mi_edittime'=>'最后修改时间','mi_jointime'=>'创建时间','mi_publishtime'=>'发行时间'),'default'=>'mi_edittime'),
	    'search_time'=>array('option'=>array('mi_edittime'=>'最后修改时间'),'default'=>'mi_edittime'),
	    'search_delflag'=>array('option'=>array(0=>'未删除',1=>'已删除',2=>'全部'),'default'=>0),
	    'search_status'=>array('option'=>array(2=>'全部',0=>'已发布',1=>'未发布'),'default'=>2),
	    'search_audit_status'=>array('option'=>array(2=>'全部',0=>'已审核',1=>'未审核'),'default'=>2),
	    'search_provider'=>array('option'=>array(0=>'全部',11=>'爱奇艺',12=>'音乐台'),'default'=>0),
	    'search_prohibit'=>array('option'=>array(5=>'全部',0=>'有版权',1=>'白名单',2=>'灰名单',3=>'黑名单',4=>'屏蔽名单'),'default'=>5),
	),
	QUKU_TYPE_YINGSHI => array(
	    'search_field'=>array('option'=>array('yi_title'=>'影视剧名称','yi_globalid' => '影视ID',"si_title" => "歌曲名","si_globalid"=>"歌曲ID","ai_album"=>"专辑名","ai_globalid"=>"专辑ID", 'yi_joinuser'=>'创建人','yi_edituser'=>'最后修改人',"awr_artist_name"=>"艺人"),'default'=>'yi_title'),
	    'search_field2'=>array('option'=>array('yi_versions'=>'版本','yi_joinuser'=>'创建人','mi_edituser'=>'最后修改人','mi_joinuser'=>'创建人',"awr_artist_name"=>"艺人"),'default'=>'yi_versions'),
	    'search_order'=>array('option'=>array('yi_edittime'=>'最后修改时间','yi_jointime'=>'创建时间','yi_publishtime'=>'发行时间'),'default'=>'yi_edittime'),
	    'search_time'=>array('option'=>array('yi_edittime'=>'最后修改时间'),'default'=>'yi_edittime'),
	    'search_delflag'=>array('option'=>array(0=>'未删除',1=>'已删除',2=>'全部'),'default'=>0),
	    'search_status'=>array('option'=>array(2=>'全部',0=>'已发布',1=>'未发布'),'default'=>2),
	    'search_audit_status'=>array('option'=>array(2=>'全部',0=>'已审核',1=>'未审核'),'default'=>2),
	),
	QUKU_TYPE_ALBUM=>array(
	'search_field'=>array('option'=>array('ai_album'=>'专辑名','ai_globalid' => '专辑id','ai_publishcompany'=>'发行公司','awr_artist_name'=>'明星名', 'ai_joinuser'=>'创建人','ai_edituser'=>'最后修改人','td_name'=>'标签名','ai_productid'=>'产品号','ai_source'=>'来源(开放平台=1000)'),'default'=>'ai_album'),
	'search_field2'=>array('option'=>array('awr_artist_name'=>'明星名', 'ai_joinuser'=>'创建人','ai_edituser'=>'最后修改人','ai_album'=>'专辑名','ai_publishcompany'=>'发行公司'),'default'=>'awr_artist_name'),
	'search_order'=>array('option'=>array('ai_edittime'=>'最后修改时间','ai_jointime'=>'创建时间','ai_publishtime'=>'发行时间', 'ai_album' => '专辑名','ai_publishcompany'=>'发行公司',),'default'=>'ai_edittime','convert'=>array('ai_album','ai_publishcompany')),
	'search_time'=>array('option'=>array('ai_edittime'=>'最后修改时间'),'default'=>'ai_edittime'),
	'search_audit_status'=>array('option'=>array(2=>'全部',0=>'已审核',1=>'未审核'),'default'=>2),
	'search_delflag'=>array('option'=>array(0=>'未删除',1=>'已删除',2=>'全部'),'default'=>0),
	'search_status'=>array('option'=>array(2=>'全部',0=>'已发布',1=>'未发布'),'default'=>2),
	),
	QUKU_TYPE_SHOW=>array(
	'search_field'=>array('option'=>array('sn_title'=>'演出名','sn_globalid' => '演出id','awr_artist_name'=>'明星名', 'sn_joinuser'=>'创建人','sn_edituser'=>'最后修改人'),'default'=>'sn_title'),
	'search_order'=>array('option'=>array('sn_edittime'=>'最后修改时间','sn_jointime'=>'创建时间','sn_begintime'=>'开始时间', 'sn_endtime' => '结束时间','sn_title'=>'演出名',),'default'=>'sn_edittime'),
	'search_time'=>array('option'=>array('sn_edittime'=>'最后修改时间'),'default'=>'sn_edittime'),
	'search_delflag'=>array('option'=>array(0=>'未删除',1=>'已删除',2=>'全部'),'default'=>0),
	'search_status'=>array('option'=>array(2=>'全部',0=>'已发布',1=>'未发布'),'default'=>2),
	),
	QUKU_TYPE_TAG=>array(
	'search_field'=>array('option'=>array('td_name'=>'标签名','ts_word'=>'同义词'),'default'=>'td_name'),
	'search_order'=>array('option'=>array('td_name'=>'标签名'),'default'=>'td_name'),
	),
	QUKU_TYPE_OPTION=>array(
	'search_field'=>array('option'=>array('od_word'=>'单词','od_spell_code'=>'拼音'),'default'=>'od_word'),
	'search_order'=>array('option'=>array('od_spell_code'=>'拼音', 'od_category'=>'类别',),'default'=>'od_spell_code'),
	),
	QUKU_TYPE_USER=>array(
	'search_field'=>array('option'=>array('ub_username'=>'用户名'),'default'=>'ub_username'),
	'search_order'=>array('option'=>array('ub_username'=>'用户名'),'default'=>'ub_username','convert'=>array('ub_username')),
	'search_delflag'=>array('option'=>array(0=>'未删除',1=>'已删除'),'default'=>0),
	),
	QUKU_TYPE_OPERATE=>array(
	'search_field'=>array('option'=>array('or_itemid'=>'信息id','or_title' => '信息名称','or_edituser'=>'最后修改人'),'default'=>'or_itemid'),
	'search_order'=>array('option'=>array('or_edittime'=>'最后修改时间','or_edituser'=>'最后修改人'),'default'=>'or_edittime'),
	'search_time'=>array('option'=>array('or_edittime'=>'最后修改时间'),'default'=>'or_edittime'),
	'search_type'=>array('option'=>array(1=>'单曲',2=>'专辑',3=>'明星'),'default'=>1),
	'search_audit_flag'=>array('option'=>array(1=>'未审核',0=>'已审核',2 => '不合格', 3=>'全部'),'default'=>1),
	),
	QUKU_TYPE_OPEN_USER=>array(
	'search_field'=>array('option'=>array(''=>'全部','ou_id'=>'申请ID','ou_company'=>'公司名称','ou_legal_rep'=>'法人代表','ou_contact_name'=>'联系人'),'default'=>''),
	'search_order'=>array('default'=>'ou_edittime'),
	'search_status'=>array('option'=>array(0=>'待认证',1=>'认证通过',2=>'认证失败',4=>'已封禁'),'default'=>0),
	),
);

$config['search_input_field']=array(
	'common'=>array(array('field'=>'search_content','default'=>''),array('field'=>'search_page_id','default'=>1),array('field'=>'search_starttime'),array('field'=>'search_endtime')),
	QUKU_TYPE_ARTIST=>array(),
	QUKU_TYPE_SONG=>array(
	array('field'=>'search_content2','default'=>'')),
	QUKU_TYPE_ALBUM=>array(
	array('field'=>'search_content2','default'=>'')),
	QUKU_TYPE_SHOW=>array(
	),
	QUKU_TYPE_TAG=>array(),
	QUKU_TYPE_MV => array(array('field'=>'search_content2','default'=>'')),
	QUKU_TYPE_YINGSHI => array(array('field'=>'search_content2','default'=>'')),
	QUKU_TYPE_OPTION=>array(),
	QUKU_TYPE_USER=>array(),
	QUKU_TYPE_OPERATE=>array(),
	QUKU_TYPE_OPEN_USER=>array(array('field'=>'search_content','default'=>''),array('field'=>'search_page_id','default'=>1)),
);

$config['form_filter_field']=array(
QUKU_TYPE_ARTIST=>array('ab_aliasname','ab_translatename','ab_relatestars','ab_synonym'),
QUKU_TYPE_SONG=>array(
'si_aliastitle',
'si_translatename',
'si_synonym',
'si_language',
),
QUKU_TYPE_ALBUM=>array(
'ai_aliasalbum',
'ai_translatename',
'ai_language',
'ai_synonym',
),
QUKU_TYPE_SHOW=>array(
//'sn_detailtime',
),
QUKU_TYPE_TAG=>array(),
QUKU_TYPE_MV => array(
    "mi_versions",
    "mi_label",
    "mi_subtitle",
    ),
QUKU_TYPE_OPTION=>array(),
QUKU_TYPE_USER=>array(),
QUKU_TYPE_MV => array(
    "mi_aliastitle",
    "mi_subtitle"
    ),
QUKU_TYPE_YINGSHI => array(
    'yi_aliastitle',
    'yi_translatename',
    'yi_language',
    "yi_main",
    "yi_guest",
    "yi_director",
    "yi_versions",
    "yi_session",
    ),
);

//qianqian lrc
$config['LRYCS_ADDR_LIST']   = 'http://jx-qianqian10.jx/lrctools/getlrc.php?type=search&title=%s&artist=%s&crypt=%s&isutf8=1';
$config['LRYCS_ADDR_DETAIL'] = 'http://jx-qianqian10.jx/lrctools/getlrc.php?type=get&id=%d&key=%s&crypt=%s&isutf8=1';
$config['CRYPT_KEY'] = 'test';
$config['MAX_LRC_NUM'] = 5;


$config['audit_fields']=array(
QUKU_TYPE_ARTIST=>array(
'ab_name'=>array('value'=>1,'explain'=>'明星名'),
'ab_birthday'=>array('value'=>2,'explain'=>'生日'),
'ab_area'=>array('value'=>4,'explain'=>'地区'),
'ab_info'=>array('value'=>8,'explain'=>'简介'),
'quku_pic_info'=>array('value'=>16,'explain'=>'图片'),
),
QUKU_TYPE_ALBUM=>array(
'ai_album'=>array('value'=>1,'explain'=>'专辑名'),
'quku_artist_works_ref'=>array('value'=>2,'explain'=>'歌手名'),
//'ai_allaid',
//'ab_id',
'ai_publishtime'=>array('value'=>4,'explain'=>'发行时间'),
'ai_styles'=>array('value'=>8,'explain'=>'类型'),
'ai_info'=>array('value'=>16,'explain'=>'简介'),
'quku_pic_info'=>array('value'=>32,'explain'=>'图片'),
),
QUKU_TYPE_SONG=>array(
'si_title'=>array('value'=>1,'explain'=>'歌曲名'),
'quku_artist_works_ref'=>array('value'=>2,'explain'=>'歌手名'),
//'si_allaid',
//'ab_id',
'si_versions'=>array('value'=>4,'explain'=>'版本'),
'si_language'=>array('value'=>8,'explain'=>'语言'),
'quku_songs_files'=>array('value'=>16,'explain'=>'音频'),
'quku_songs_lrcs'=>array('value'=>32,'explain'=>'歌词'),
),
);

$config["album_check_type"] = array(
    "4" => "综艺",
    /* "1" => "电影", */
    /* "2" => "电视", */
    );

$config['acl']=array(
'default'=>array(
	'create'=>array(2,3),
	'doCreate'=>array(2,3),
	'doCreateAndPub'=>array(2,3),
	'doEdit'=>array(2,3),
	'doEditAndPub'=>array(2,3),
	'pub'=>array(2,3),
	'disPub'=>array(2,3),
	'delete'=>array(2,3),
	'disDelete'=>array(2,3),
	'batchPub'=>array(2,3),
	'batchDelete'=>array(3),
	'saveInCache'=>array(1),
	'showCacheInfo'=>array(1,2,3,0),
	'synchronize'=>array(2,3),
),
'index'=>array(
'topmenu'=>array(1,2,3,0,4),
'menu'=>array(1,2,3,0,4),
'bar'=>array(1,2,3,0,4),
'welcome'=>array(1,2,3,0,4),
),
'pic'=>array(),
'lrc'=>array(),
'media'=>array(),
'artist'=>array(),
'song'=>array(),
'album'=>array(),
'mv'=>array(),
"yingshi" => array(),
'show'=>array(),
'tag'=>array(),
'openuser'=>array(),
'option'=>array(
	'doCreate'=>array(3),
	'doEdit'=>array(3),
	'delete'=>array(3)),
'user'=>array(
	'doCreate'=>array(3),
	'doEdit'=>array(3),
	'delete'=>array(3),
	'search'=>array(3)),
'operate'=>array()
,
'search'=>array(),
"batchoperation"=>array(),
'error'=>array(),
);

$config['data_path']=ROOT_PATH.'data/';
$config['error_message']=array(1=>'对不起，您没有权限进入系统',2=>'对不起，您没有权限进行此操作');

$config['open_user_field']=array(
'ou_id'=>'id',
'ou_passport_id'=>'passport 用户id',
'ou_company'=>'公司名称',
'ou_legal_rep'=>'法人代表',
'ou_contact_name'=>'联系人姓名',
'ou_address'=>'联系人地址',
'ou_telephone'=>'联系人固定电话',
'ou_cellphone'=>'联系人手机号',
'ou_email'=>'邮箱',
'ou_postcode'=>'邮编',
'ou_user_type'=>'用户类型（0=未知，1=公司，2=个人，3=工作室）',
'ou_edituser'=>'最后操作人',
'ou_edittime'=>'最后更新时间',
'ou_jointime'=>'注册时间',
'ou_status'=>'当前状态（0=待认证，1=认证通过，2=认证失败，3=封禁）',
'ou_approve_user'=>'认证人',
'ou_approve_time'=>'认证时间',
'ou_forbid_user'=>'封禁人',
'ou_forbid_time'=>'封禁时间',
'ou_complete'=>'完整度',
'ou_fail_reason'=>'认证失败原因（1=材料未通过审核,2=无法认证资质）',
);
/* End of file config.php */
/* Location: ./application/config/config.php */
